<img src="Images/PU.png" width="100%">

## Course Name : AI 702 Deep Learning for Professionals  
#### Notebook compiled by : Bhushan Garware, Project Lead at Learning and Development  
** Important ! ** For internal circulation olny

## Boston Housing Price Prediction 
Let's work on a new
dataset, the Housing Dataset, which contains information about houses in the
suburbs of Boston collected by D. Harrison and D.L. Rubinfeld in 1978.
<img src="Images/boston_house.jpg" width="50%">

Source: [https://archive.ics.uci.edu/ml/datasets/Housing](https://archive.ics.uci.edu/ml/datasets/Housing)

Attributes:
    
<pre>
1. CRIM      per capita crime rate by town
2. ZN        proportion of residential land zoned for lots over 
                 25,000 sq.ft.
3. INDUS     proportion of non-retail business acres per town
4. CHAS      Charles River dummy variable (= 1 if tract bounds 
                 river; 0 otherwise)
5. NOX       nitric oxides concentration (parts per 10 million)
6. RM        average number of rooms per dwelling
7. AGE       proportion of owner-occupied units built prior to 1940
8. DIS       weighted distances to five Boston employment centres
9. RAD       index of accessibility to radial highways
10. TAX      full-value property-tax rate per $10,000
11. PTRATIO  pupil-teacher ratio by town
12. B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks 
                 by town
13. LSTAT    % lower status of the population
14. MEDV     Median value of owner-occupied homes in $1000's
</pre>

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

df = pd.read_csv('./Datasets/housing.data', header=None, sep='\s+')

df.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS','NOX', 'RM', 'AGE', 'DIS', 'RAD','TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(12), int64(2)
memory usage: 55.4 KB


In [4]:
df = df.values

In [5]:
X = df[:,0:13]
y = df[:,13]

In [6]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [9]:
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

### Data Standadization 

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)

In [12]:
# Scale the train set
X_train = scaler.transform(X_train)
# Scale the test set
X_test = scaler.transform(X_test)

# Keras Neural Network 

In [13]:
from keras.models import Sequential

Using TensorFlow backend.


In [14]:
from keras.layers import Dense

In [15]:
model = Sequential()

### Input layer 

In [16]:
model.add(Dense(26, input_dim=13, kernel_initializer='normal', activation='relu'))

#### Hidden Layer to be inserted to see its effect on accuracy and cost

In [ ]:
model.add(Dense(13, kernel_initializer='normal', activation='relu'))

In [ ]:
model.add(Dense(6, kernel_initializer='normal', activation='relu'))

### Output layer

In [17]:
model.add(Dense(1, kernel_initializer='normal'))

### Compile Model 

In [18]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [19]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 26)                364       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 27        
Total params: 391
Trainable params: 391
Non-trainable params: 0
_________________________________________________________________
None


### Train model 

In [20]:
model.fit(X_train, y_train, epochs=1460, batch_size=2, verbose=1)

Epoch 1/1460
354/354 [==============================] - 1s 2ms/step - loss: 565.0057
Epoch 2/1460
354/354 [==============================] - 0s 1ms/step - loss: 355.2196
Epoch 3/1460
354/354 [==============================] - 0s 1ms/step - loss: 135.0749
Epoch 4/1460
354/354 [==============================] - 0s 1ms/step - loss: 57.4459
Epoch 5/1460
354/354 [==============================] - 1s 1ms/step - loss: 37.2225
Epoch 6/1460
354/354 [==============================] - 0s 1ms/step - loss: 30.3234
Epoch 7/1460
354/354 [==============================] - 1s 1ms/step - loss: 27.4773
Epoch 8/1460
354/354 [==============================] - 1s 1ms/step - loss: 25.6776
Epoch 9/1460
354/354 [==============================] - 0s 1ms/step - loss: 24.5161
Epoch 10/1460
354/354 [==============================] - 1s 1ms/step - loss: 23.4021
Epoch 11/1460
354/354 [==============================] - 0s 1ms/step - loss: 22.5225
Epoch 12/1460
354/354 [==============================] - 0s 1ms/step - 

354/354 [==============================] - 0s 901us/step - loss: 7.1748
Epoch 98/1460
354/354 [==============================] - ETA: 0s - loss: 6.428 - 0s 875us/step - loss: 7.1419
Epoch 99/1460
354/354 [==============================] - 0s 788us/step - loss: 7.1620
Epoch 100/1460
354/354 [==============================] - 0s 1ms/step - loss: 7.0860
Epoch 101/1460
354/354 [==============================] - 0s 943us/step - loss: 7.0436
Epoch 102/1460
354/354 [==============================] - 0s 836us/step - loss: 7.0727
Epoch 103/1460
354/354 [==============================] - 0s 906us/step - loss: 7.0519
Epoch 104/1460
354/354 [==============================] - 0s 864us/step - loss: 7.0542
Epoch 105/1460
354/354 [==============================] - 0s 884us/step - loss: 7.0180
Epoch 106/1460
354/354 [==============================] - 0s 813us/step - loss: 6.9772
Epoch 107/1460
354/354 [==============================] - 0s 844us/step - loss: 6.9800
Epoch 108/1460
354/354 [==============

354/354 [==============================] - 0s 771us/step - loss: 5.7890
Epoch 192/1460
354/354 [==============================] - 0s 816us/step - loss: 5.8039
Epoch 193/1460
354/354 [==============================] - 0s 915us/step - loss: 5.7869
Epoch 194/1460
354/354 [==============================] - 0s 807us/step - loss: 5.7187
Epoch 195/1460
354/354 [==============================] - 0s 782us/step - loss: 5.8535
Epoch 196/1460
354/354 [==============================] - 0s 870us/step - loss: 5.7439
Epoch 197/1460
354/354 [==============================] - 0s 813us/step - loss: 5.7766
Epoch 198/1460
354/354 [==============================] - 0s 793us/step - loss: 5.8935
Epoch 199/1460
354/354 [==============================] - 0s 788us/step - loss: 5.7510
Epoch 200/1460
354/354 [==============================] - 0s 807us/step - loss: 5.7340
Epoch 201/1460
354/354 [==============================] - 0s 813us/step - loss: 5.6881
Epoch 202/1460
354/354 [==============================] - 

354/354 [==============================] - 0s 1ms/step - loss: 4.8428
Epoch 285/1460
354/354 [==============================] - 0s 988us/step - loss: 4.8959
Epoch 286/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.9416
Epoch 287/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8567
Epoch 288/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8009
Epoch 289/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8628
Epoch 290/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8452
Epoch 291/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.7953
Epoch 292/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8840
Epoch 293/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.7749
Epoch 294/1460
354/354 [==============================] - 0s 1ms/step - loss: 4.8305
Epoch 295/1460
354/354 [==============================] - 1s 2ms/step - loss: 

354/354 [==============================] - 0s 957us/step - loss: 4.3196
Epoch 380/1460
354/354 [==============================] - 0s 822us/step - loss: 4.3572
Epoch 381/1460
354/354 [==============================] - 0s 844us/step - loss: 4.3814
Epoch 382/1460
354/354 [==============================] - 0s 779us/step - loss: 4.3622
Epoch 383/1460
354/354 [==============================] - 0s 827us/step - loss: 4.3752
Epoch 384/1460
354/354 [==============================] - 0s 858us/step - loss: 4.3624
Epoch 385/1460
354/354 [==============================] - 0s 774us/step - loss: 4.2809
Epoch 386/1460
354/354 [==============================] - 0s 898us/step - loss: 4.2712
Epoch 387/1460
354/354 [==============================] - 0s 802us/step - loss: 4.3157
Epoch 388/1460
354/354 [==============================] - 0s 844us/step - loss: 4.3090
Epoch 389/1460
354/354 [==============================] - 0s 771us/step - loss: 4.3824
Epoch 390/1460
354/354 [==============================] - 

354/354 [==============================] - 0s 822us/step - loss: 3.9686
Epoch 473/1460
354/354 [==============================] - 0s 861us/step - loss: 3.9931
Epoch 474/1460
354/354 [==============================] - 0s 824us/step - loss: 3.9528
Epoch 475/1460
354/354 [==============================] - 0s 810us/step - loss: 3.9765
Epoch 476/1460
354/354 [==============================] - 0s 810us/step - loss: 3.9874
Epoch 477/1460
354/354 [==============================] - 0s 949us/step - loss: 3.9928
Epoch 478/1460
354/354 [==============================] - 0s 906us/step - loss: 3.9502
Epoch 479/1460
354/354 [==============================] - 0s 785us/step - loss: 3.9995
Epoch 480/1460
354/354 [==============================] - 0s 805us/step - loss: 3.9550
Epoch 481/1460
354/354 [==============================] - 0s 785us/step - loss: 3.9571
Epoch 482/1460
354/354 [==============================] - 0s 768us/step - loss: 3.9694
Epoch 483/1460
354/354 [==============================] - 

354/354 [==============================] - 0s 1ms/step - loss: 3.5408
Epoch 567/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.6766
Epoch 568/1460
354/354 [==============================] - 0s 958us/step - loss: 3.6176
Epoch 569/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.6562
Epoch 570/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.7150
Epoch 571/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.5976
Epoch 572/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.6241
Epoch 573/1460
354/354 [==============================] - 0s 951us/step - loss: 3.6717
Epoch 574/1460
354/354 [==============================] - 0s 943us/step - loss: 3.6064
Epoch 575/1460
354/354 [==============================] - 1s 1ms/step - loss: 3.6094
Epoch 576/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.6604
Epoch 577/1460
354/354 [==============================] - 0s 1ms/step - lo

354/354 [==============================] - 0s 1ms/step - loss: 3.4603
Epoch 661/1460
354/354 [==============================] - 0s 776us/step - loss: 3.4620
Epoch 662/1460
354/354 [==============================] - 0s 757us/step - loss: 3.5472
Epoch 663/1460
354/354 [==============================] - 0s 824us/step - loss: 3.4465
Epoch 664/1460
354/354 [==============================] - 0s 779us/step - loss: 3.5373
Epoch 665/1460
354/354 [==============================] - 0s 740us/step - loss: 3.4340
Epoch 666/1460
354/354 [==============================] - 0s 774us/step - loss: 3.4714
Epoch 667/1460
354/354 [==============================] - 0s 947us/step - loss: 3.5040
Epoch 668/1460
354/354 [==============================] - 0s 809us/step - loss: 3.4745
Epoch 669/1460
354/354 [==============================] - 0s 799us/step - loss: 3.4464
Epoch 670/1460
354/354 [==============================] - 0s 743us/step - loss: 3.4569
Epoch 671/1460
354/354 [==============================] - 0s

354/354 [==============================] - 0s 824us/step - loss: 3.4227
Epoch 755/1460
354/354 [==============================] - 0s 799us/step - loss: 3.3576
Epoch 756/1460
354/354 [==============================] - 0s 974us/step - loss: 3.3668
Epoch 757/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.4045
Epoch 758/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.4185
Epoch 759/1460
354/354 [==============================] - 0s 841us/step - loss: 3.3445
Epoch 760/1460
354/354 [==============================] - 0s 771us/step - loss: 3.3567
Epoch 761/1460
354/354 [==============================] - 0s 771us/step - loss: 3.4358
Epoch 762/1460
354/354 [==============================] - 0s 743us/step - loss: 3.3564
Epoch 763/1460
354/354 [==============================] - 0s 867us/step - loss: 3.3990
Epoch 764/1460
354/354 [==============================] - 0s 1ms/step - loss: 3.4214
Epoch 765/1460
354/354 [==============================] - 0s 1ms

354/354 [==============================] - 0s 830us/step - loss: 3.3410
Epoch 849/1460
354/354 [==============================] - 0s 726us/step - loss: 3.2999
Epoch 850/1460
354/354 [==============================] - 0s 731us/step - loss: 3.3001
Epoch 851/1460
354/354 [==============================] - 0s 745us/step - loss: 3.2270
Epoch 852/1460
354/354 [==============================] - 0s 762us/step - loss: 3.3740
Epoch 853/1460
354/354 [==============================] - 0s 762us/step - loss: 3.2477
Epoch 854/1460
354/354 [==============================] - 0s 737us/step - loss: 3.3453
Epoch 855/1460
354/354 [==============================] - 0s 796us/step - loss: 3.2862
Epoch 856/1460
354/354 [==============================] - 0s 762us/step - loss: 3.3253
Epoch 857/1460
354/354 [==============================] - 0s 799us/step - loss: 3.3753
Epoch 858/1460
354/354 [==============================] - 0s 776us/step - loss: 3.3053
Epoch 859/1460
354/354 [==============================] - 

354/354 [==============================] - 0s 816us/step - loss: 3.1845
Epoch 943/1460
354/354 [==============================] - 0s 799us/step - loss: 3.2544
Epoch 944/1460
354/354 [==============================] - 0s 793us/step - loss: 3.2058
Epoch 945/1460
354/354 [==============================] - 0s 771us/step - loss: 3.2046
Epoch 946/1460
354/354 [==============================] - 0s 723us/step - loss: 3.1391
Epoch 947/1460
354/354 [==============================] - 0s 765us/step - loss: 3.3207
Epoch 948/1460
354/354 [==============================] - 0s 745us/step - loss: 3.2389
Epoch 949/1460
354/354 [==============================] - 0s 779us/step - loss: 3.2097
Epoch 950/1460
354/354 [==============================] - 0s 788us/step - loss: 3.2125
Epoch 951/1460
354/354 [==============================] - 0s 788us/step - loss: 3.2390
Epoch 952/1460
354/354 [==============================] - 0s 785us/step - loss: 3.2201
Epoch 953/1460
354/354 [==============================] - 

354/354 [==============================] - 0s 621us/step - loss: 3.1698
Epoch 1037/1460
354/354 [==============================] - 0s 615us/step - loss: 3.1414
Epoch 1038/1460
354/354 [==============================] - 0s 601us/step - loss: 3.1032
Epoch 1039/1460
354/354 [==============================] - 0s 621us/step - loss: 3.1433
Epoch 1040/1460
354/354 [==============================] - 0s 700us/step - loss: 3.1079
Epoch 1041/1460
354/354 [==============================] - 0s 604us/step - loss: 3.0862
Epoch 1042/1460
354/354 [==============================] - 0s 596us/step - loss: 3.0989
Epoch 1043/1460
354/354 [==============================] - 0s 587us/step - loss: 3.1328
Epoch 1044/1460
354/354 [==============================] - 0s 599us/step - loss: 3.1368
Epoch 1045/1460
354/354 [==============================] - 0s 726us/step - loss: 3.1124
Epoch 1046/1460
354/354 [==============================] - 0s 590us/step - loss: 3.1336
Epoch 1047/1460
354/354 [=======================

354/354 [==============================] - 0s 771us/step - loss: 2.9200
Epoch 1130/1460
354/354 [==============================] - 0s 771us/step - loss: 3.0039
Epoch 1131/1460
354/354 [==============================] - 0s 765us/step - loss: 2.9294
Epoch 1132/1460
354/354 [==============================] - 0s 810us/step - loss: 2.9551
Epoch 1133/1460
354/354 [==============================] - 0s 757us/step - loss: 2.9441
Epoch 1134/1460
354/354 [==============================] - 0s 731us/step - loss: 2.9243
Epoch 1135/1460
354/354 [==============================] - 0s 754us/step - loss: 2.9134
Epoch 1136/1460
354/354 [==============================] - 0s 802us/step - loss: 3.0297
Epoch 1137/1460
354/354 [==============================] - 0s 774us/step - loss: 2.9473
Epoch 1138/1460
354/354 [==============================] - 0s 776us/step - loss: 2.9607
Epoch 1139/1460
354/354 [==============================] - 0s 810us/step - loss: 2.9527
Epoch 1140/1460
354/354 [=======================

354/354 [==============================] - 0s 754us/step - loss: 2.8836
Epoch 1223/1460
354/354 [==============================] - 0s 757us/step - loss: 2.8589
Epoch 1224/1460
354/354 [==============================] - 0s 819us/step - loss: 2.9283
Epoch 1225/1460
354/354 [==============================] - 0s 872us/step - loss: 2.8424
Epoch 1226/1460
354/354 [==============================] - 0s 751us/step - loss: 2.8811
Epoch 1227/1460
354/354 [==============================] - 0s 765us/step - loss: 2.8480
Epoch 1228/1460
354/354 [==============================] - 0s 819us/step - loss: 2.8468
Epoch 1229/1460
354/354 [==============================] - 0s 759us/step - loss: 2.9172
Epoch 1230/1460
354/354 [==============================] - 0s 802us/step - loss: 2.8485 0s - loss: 1
Epoch 1231/1460
354/354 [==============================] - 0s 844us/step - loss: 2.8685
Epoch 1232/1460
354/354 [==============================] - 0s 748us/step - loss: 2.8175
Epoch 1233/1460
354/354 [==========

354/354 [==============================] - 0s 813us/step - loss: 2.8101
Epoch 1315/1460
354/354 [==============================] - 0s 799us/step - loss: 2.7478
Epoch 1316/1460
354/354 [==============================] - 0s 855us/step - loss: 2.8039
Epoch 1317/1460
354/354 [==============================] - 0s 796us/step - loss: 2.8535
Epoch 1318/1460
354/354 [==============================] - 0s 791us/step - loss: 2.7544
Epoch 1319/1460
354/354 [==============================] - 0s 793us/step - loss: 2.7785
Epoch 1320/1460
354/354 [==============================] - 0s 810us/step - loss: 2.7881
Epoch 1321/1460
354/354 [==============================] - 0s 816us/step - loss: 2.8275
Epoch 1322/1460
354/354 [==============================] - 0s 807us/step - loss: 2.8173
Epoch 1323/1460
354/354 [==============================] - 0s 793us/step - loss: 2.8645
Epoch 1324/1460
354/354 [==============================] - 0s 788us/step - loss: 2.8678
Epoch 1325/1460
354/354 [=======================

354/354 [==============================] - 0s 782us/step - loss: 2.7228
Epoch 1407/1460
354/354 [==============================] - 0s 717us/step - loss: 2.7304
Epoch 1408/1460
354/354 [==============================] - 0s 776us/step - loss: 2.7603
Epoch 1409/1460
354/354 [==============================] - 0s 884us/step - loss: 2.7251
Epoch 1410/1460
354/354 [==============================] - 0s 779us/step - loss: 2.7281
Epoch 1411/1460
354/354 [==============================] - 0s 810us/step - loss: 2.7150
Epoch 1412/1460
354/354 [==============================] - 0s 802us/step - loss: 2.7268
Epoch 1413/1460
354/354 [==============================] - 0s 830us/step - loss: 2.7022
Epoch 1414/1460
354/354 [==============================] - 0s 762us/step - loss: 2.7231
Epoch 1415/1460
354/354 [==============================] - 0s 779us/step - loss: 2.7120
Epoch 1416/1460
354/354 [==============================] - 0s 737us/step - loss: 2.7747
Epoch 1417/1460
354/354 [=======================

In [21]:
y_pred = model.predict(X_test)

In [22]:
score = model.evaluate(X_test, y_test,verbose=0)
print(score)

14.986587022480212


#### Let us predict of the first sample from our given data set (actual price is 24)  

In [23]:
import numpy as np

In [24]:
X_temp= np.array([0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98])

In [25]:
X_temp

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [26]:
X_temp=np.reshape(X_temp, (1, 13))

In [27]:
X_temp

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [28]:
X_temp = scaler.transform(X_temp)

In [29]:
X_temp

array([[-0.40184593,  0.26209891, -1.25556098, -0.26360274, -0.15678047,
         0.38026709, -0.13550824,  0.15863568, -0.96459077, -0.62096677,
        -1.4284095 ,  0.42454294, -1.05548145]])

In [30]:
model.predict(X_temp)

array([[24.549637]], dtype=float32)